tasks:
  - init: |
      nix profile install .#nil
      nix profile install .#clang-tools
      nix profile install .#lldb
      mkdir -p /home/gitpod/.config/nix &&
      echo 'sandbox = false' >> /home/gitpod/.config/nix/nix.conf
      nix develop

vscode:
  extensions:
    - jnoortheen.nix-ide
    - vadimcn.vscode-lldb
    - llvm-vs-code-extensions.vscode-clangd
