tasks:
  - init: |
      direnv allow
      mkdir -p /home/gitpod/.config/nix &&
      echo 'sandbox = false' >> /home/gitpod/.config/nix/nix.conf
      nix-env -i nil clang-tools
      nix develop

vscode:
  extensions:
    - jnoortheen.nix-ide
