tasks:
  - init: |
      nix-env -i nil
      nix-env -i clang-tools
      mkdir -p /home/gitpod/.config/nix &&
      echo 'sandbox = false' >> /home/gitpod/.config/nix/nix.conf
      nix develop

vscode:
  extensions:
    - jnoortheen.nix-ide
