:doctype: book
:imagesdir: images
:stylesheet: paper.css
:last-update-label!:
:source-highlighter: highlight.js
:highlightjs-theme: thesis
:highlightjsdir: libraries/highlightjs
:stem:
:toc: macro
:xrefstyle: short
ifndef::env-vscode[]
:kroki-fetch-diagram: true
:kroki-default-options: inline
endif::env-vscode[]

image::../assets/logo_hda.svg[role=logo]

[.university.text-center]
Darmstadt University of Applied Sciences

[.faculty.text-center]
Faculty of Computer Science

[discrete#main-title]
= Lab report for the first high-performance computing exercise

[.presented-by.text-center]
by +
****REMOVED**** ***REMOVED*** +
****REMOVED**** ***REMOVED***

:part-signifier: Part
:listing-caption: Listing

== Evaluation 

Figures, tables, and listings are automatically numbered and added to their respective list after the table of contents.

=== Setup

We tested for different parallel implementations for calculating pi. One uses cpp threads, one uses openmp, one c implementation using MPI and one CPP implementation useing MPI. We tested the implementations with a 1 2 4 and 8 threads on Lennarts computer (shown in <<our-computers>>). 

.Weird chart
:chart-id: id=weird-chart
:vega-lite-filename: processed-assets/compiler-comparison.vl.json
include::scripts/vega-chart.adoc[]

<<weird-chart>> shows our first measurements. You can see two different performance characteristics, one for the MPI implementations and one for the other implementations. On further investigation we discovered, that the MPI implementations actually used gcc, while the other implementations used clang. This is because the MPI compiler uses gcc by default if the `OMPI_CC`. We noticed that there is a significant performance difference between the executables created with GCC and clang. <<compiler-chart>> compares the performance of the different compilers.

Because of this, we decided to only use clang for our further measurements. The optimization level was set to `-O3` for all measurements. We measured the performance for 1, 2, 4 and 8 threads. If not specified otherwise the value for n is set to 8192.

.Example of openMP in CPP
[source#openmp-example,cpp]
----
include::KickOff/openMP-pi.cpp[tag=openmp]
----

=== Measurements

.This chart
:chart-id: id=this-chart
:vega-lite-filename: processed-assets/mpi-cpp.vl.json
include::scripts/vega-chart.adoc[]

.That chart
:chart-id: id=that-chart
:vega-lite-filename: processed-assets/implementation-comparison-fixed-n.vl.json
include::scripts/vega-chart.adoc[]

.Important chart
:chart-id: id=important-chart
:vega-lite-filename: processed-assets/implementation-comparison-fixed-threads.vl.json
include::scripts/vega-chart.adoc[]

== Appendix

[#our-computers,cols="1,2,2"]
.Our computers
|===
|sdfs
|Lennart
|Björn 

|CPU
|i9-11950H @ 2.6GHz
|i5-7200U @ 2.5GHz

|CPU-Kerne / Threads
|8 / 16
|2 / 4

|GPU
|RTX3070 mobile
|Intel HD Graphics 620

|OS
|Nix OS unstable/latest - 64 Bit
|Ubuntu 23.04 - 64 Bit

|RAM (GB)
|32
|8
|=== 

include::scripts/trailing-scripts.adoc[]