:doctype: book
:imagesdir: images
:stylesheet: paper.css
// Disable generating an update label at the bottom of the doc.
:last-update-label!:
// Setup highlight.js to use a local version with a local stylesheet
:source-highlighter: highlight.js
:highlightjs-theme: thesis
:highlightjsdir: libraries/highlightjs
// Enable rendering math equations
:stem:
// Generate a table of contents at the toc macro
// Also disabling section numbers for now, as we only start numbering after the toc. See the macros there
:toc: macro
:toclevels: 3
:sectanchors:
// Disable the title page
// We will build the title page manually for maximum flexibility
:notitle:
:title-page: false
// Refer to things like "Figure 1" instead of by their name
:xrefstyle: short
// Prefetch and inline diagrams with kroki but not in vscode
ifndef::env-vscode[]
:kroki-fetch-diagram: true
:kroki-default-options: inline
endif::env-vscode[]

image::../assets/logo_hda.svg[role=logo]

[.university.text-center]
Darmstadt University of Applied Sciences

[.faculty.text-center]
Faculty of Computer Science

[discrete#main-title]
= Lab report for the first high-performance computing exercise

[.presented-by.text-center]
by +
****REMOVED**** ***REMOVED*** +
****REMOVED**** ***REMOVED***


// The table of contents gets inserted here.
toc::[]

:part-signifier: Part
:listing-caption: Listing

== Techstack

[cols="1,2,2"]
|===
|
|Lennart
|Björn 

|CPU
|i9-11950H @ 2.6GHz
|i5-7200U @ 2.5GHz

|CPU-Kerne / Threads
|8 / 16
|2 / 4

|GPU
|RTX3070 mobile
|Intel HD Graphics 620

|OS
|Nix OS unstable/latest - 64 Bit
|Ubuntu 23.04 - 64 Bit

|RAM (GB)
|32
|8
|=== 

== Auswertung 

Figures, tables, and listings are automatically numbered and added to their respective list after the table of contents.

=== Using figures

All chart types except for vega-lite should just be used as asciidoctor-kroki charts. You can reference your chart in the text like <<sample-nomnoml-chart>>, by giving it an id, in this case, `sample-nomnoml-chart`.

.Sample nomnoml chart
[nomnoml,id=sample-nomnoml-chart]
....
[<actor>Jolly;Sailor]
[Jolly;Sailor]->[Pirate]
[Jolly;Sailor]->[rum]

[Pirate|
  [beard]--[parrot]
  [beard]-:>[foul mouth]
]
[Pirate]-> *[rum|tastiness: int|swig()]
[<abstract>Marauder]<:--[Pirate]

[<table>mischief| bawl | sing || yell | drink ]
[Pirate] - 0..7[mischief]

#gutter: 10
#lineWidth: 1.25
#stroke: #000000
#font: Spectral
#fill: #f7f8f7; #ffffff; #f7f8f7; #ffffff; #f7f8f7; #ffffff
....

.Source for the section above
[source,asciidoc]
----
All chart types except for vega-lite should just be used as asciidoctor-kroki charts. You can reference your chart in the text like <<sample-nomnoml-chart>>, by giving it an id, in this case, `sample-nomnoml-chart`.

.Sample nomnoml chart
[nomnoml,id=sample-nomnoml-chart]
....
[<actor>Jolly;Sailor]
[Jolly;Sailor]->[Pirate]
[Jolly;Sailor]->[rum]

[Pirate|
  [beard]--[parrot]
  [beard]-:>[foul mouth]
]
[Pirate]-> *[rum|tastiness: int|swig()]
[<abstract>Marauder]<:--[Pirate]

[<table>mischief| bawl | sing || yell | drink ]
[Pirate] - 0..7[mischief]

#gutter: 10
#lineWidth: 1.25
#stroke: #000000
#font: Spectral
#fill: #f7f8f7; #ffffff; #f7f8f7; #ffffff; #f7f8f7; #ffffff
....
----

.Sample wavedrom chart
[wavedrom,id=sample-wavedrom-chart]
....
include::assets/keccak_clang_speed.wavejson.json[]
....

.Source for the wavedrom chart
[source,asciidoc]
----
.Sample wavedrom chart
[wavedrom,id=sample-wavedrom-chart]
....
\include::assets/keccak_clang_speed.wavejson.json[]
....
----

To make the chart extend over the margins of the page, add a `slightly-oversized`, `oversized`, or `completely-oversized` to the chart.

.Source for the section above
.Sample graphviz graph
[graphviz.slightly-oversized,id=minmax-speed-cfg,width=570px]
....
include::assets/minmax_speed_control_flow.dot[]
....

[source,asciidoc]
----
.Sample graphviz graph
[graphviz.slightly-oversized,id=minmax-speed-cfg,width=570px]
....
\include::assets/minmax_speed_control_flow.dot[]
....
----

==== Data-driven charts

Vega-lite is the preferred way to display any data-driven charts. You use the included `vega-chart.adoc` script to include vega-lite charts. It detects if the document is currently built for a browser or as a PDF. If the document is built for a browser, it will include the chart directly via the Vega javascript library. That way, the chart supports tooltips and other interactive features.

[source,asciidoc]
----
.Sample vega-lite chart
:chart-id: id=minmax-area
:vega-lite-filename: processed-assets/minmax_overview_area.vl.json
\include::scripts/vega-chart.adoc[]
----

.Sample vega-lite chart
:chart-id: id=minmax-area
:vega-lite-filename: processed-assets/minmax_overview_area.vl.json
include::scripts/vega-chart.adoc[]

=== Using source listings

Asciidoc also supports source listings. A short verilog listing is shown in <<short-verilog-listing>>.

.Short Verilog listing
[source#short-verilog-listing,verilog]
----
module Blinker (input clock, output blinker);
  reg [6:0] counter = 0;
  reg state = 0;
  always @(posedge clock) begin
    counter <= counter + 1;
    if (counter == 9) begin
      state   <= ~state;
      counter <= 0;
    end
  end
  assign blinker = state;
endmodule
----

<<long-rust-listing>> shows a long Rust listing. This template has a `.linenums` class that can be added to code listings to enable line numbers. The normal AsciiDoc `linenums` attribute is not supported.

.Long rust listing with line numbers
[source#long-rust-listing.linenums,rust]
----
include::assets/long_rust_listing.rs[tag=function]
----

Your code should be no wider than 80 characters. If it is, try using the `oversized` classes to avoid unnecessary line breaks.

=== Using tables

Asciidoc supports tables. A simple table is shown in <<somewhat-complex-table>>.

.Somewhat complex table
[#somewhat-complex-table,cols="1,1,3"]
|===
|Port |Size per channel in bits |Description

|`Mout_oe_ram`
|stem:[1]
|Set to 1 to read from the channel.

|`Mout_we_ram`
|stem:[1]
|Set to 1 to write to the channel.

|`Mout_data_ram_size`
|stem:[log_2("dataWidth") + 1]
|Set the width of bits that should be written to the memory. It can be a value between 0 and the width of your data.

|`Mout_addr_ram`
|stem:["addressWidth"]
|Select the address this channel should operate on.

|`M_Wdata_ram`
|stem:["dataWidth"]
|Contains the data that will be written to memory if `Mout_we_ram` is set.

|`M_Rdata_ram`
|stem:["dataWidth"]
|Contains the data that was read from memory if `Mout_oe_ram` was set in the last cycle.

|`M_DataRdy`
|stem:[1]
|Nonzero if the memory is not ready.

|===

== Referencing other parts of the document

Asciidoc supports referencing other parts of the document. To reference other parts of the document, you can use the `<<id>>` syntax. The template styles them like this:
<<somewhat-complex-table>> and <<short-verilog-listing>> and <<sample-wavedrom-chart>> and <<_using_figures>> and <<invalid-reference>>

=== Using abbreviations

When you first use abbreviations, you should introduce them like field-programmable gate array (FPGA). You should also add them to the <<_list_of_abbreviations>>. Every abbreviation added to that list will automatically be linked when it is used in the document. 

For example, we can just use FPGA, HLS, RAII, and LLVM IR in any sentence, and they will be linked without any special markup.

I also recommend adding a link to a more detailed web source like Wikipedia to every entry in the list of abbreviations. I usually have the list of abbreviations as the first section after the main content.

To see an example of a list of abbreviations, look at the source for <<_list_of_abbreviations>>.

=== Citations and bibliography

This template uses the built-in bibliography support of Asciidoctor. It is relatively basic, but I found it to work really well in practice. The Readme goes into more detail on how you can structure your bibliography; alternatively, you can directly look into the source of this document.

To cite a source, just reference it like a figure, table, or section. References to sources should grammatically not be a part of your sentence.

.Example
The Rust programming language <<Kla23>> is a modern systems programming language. It is the most loved programming language of the last years <<Sta16>> <<Sta20>> <<Sta23>>. On an unrelated note, Microsoft uses FPGAs to accelerate their Bing search engine <<Nan16>>, and Bambu <<Fer21>> is a framework for HLS. I don't think Microsoft uses Bambu for their FPGAs; they probably use SystemVerilog, the most common language for hardware design <<Soz22>>.

=== Referencing things from the appendix

Just add an extra chapter named Appendix after the references and dump your figures and whatnot there. You can reference them like any other figure. <<extra-long-rust-listing>> was banished into the appendix because I needed to put something there as an example.

== Conclusion

In conclusion, the Asciidoctor.js thesis template offers a flexible, readable, and user-friendly approach to scientific writing. By leveraging web technologies, the template enables easy customization and modification of the document's design. The inclusion of interactive figures using asciidoctor-kroki and vega-lite enhances the visual presentation of data and improves the overall reading experience. The template's support for source listings and syntax highlighting ensures clear and legible code representation. It is important to note that this section was generated with an AI language model trained by OpenAI because a conclusion does not make sense in a dummy document like this. With its comprehensive documentation and practical examples, the Asciidoctor.js thesis template empowers users to create well-structured and visually appealing scientific theses. By combining the simplicity of markdown-like syntax with the power of web technologies, this template sets a new standard for scientific writing, making the process more accessible and enjoyable for researchers and students alike.

== Future work

This template is by no means perfect; there are still some things that could be improved. For example, the template does not support footnotes because I don't need them. Images are also untested but should work exactly like figures. Admonitions look acceptable but could definitely be fancier. But who uses admonitions in scientific writing anyway? There are probably more AsciiDoc features I don't use that may not work properly. As the default stylesheets are included in the template, most should still look fine. I also do not like blue links. Maybe I should style them differently.

The template could also be adjusted to work well with Asciidoctor slides, but I have not tried that yet. Thanks for reading to the end, have a nice day and a cookie 🍪.

== Appendix


.Extra long rust listing with line numbers
[source#extra-long-rust-listing.linenums,rust]
----
include::assets/long_rust_listing.rs[]
----

include::scripts/trailing-scripts.adoc[]